# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[tw]
  languageCode = "tw"
  contentDir = "content/tw"
  title = "量子奈米光學"
  [tw.params]
    description = "Site description in Chinese..."
  [[tw.menu.main]]
    name = "關於"
    url = "#about"
    weight = 1
    
[[tw.menu.main]]
  name = "Posts"
  url = "post/"
  weight = 20

[[tw.menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[tw.menu.main]]
  name = "發表"
  url = "#featured"
  weight = 40

[[tw.menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 60
